<?php namespace ProcessWire;

include(__DIR__.'/vendor/autoload.php');

// Twig
use Twig\Loader\FilesystemLoader, Twig\Environment;
// Pauldro Twig
use Pauldro\Twig\TwigDecorator;

/**
 * Twig
 * Autoloads Twig
 * 
 * @property  FileSystemLoader $loader
 * @property  Environment      $twig
 */
class Twig extends WireData implements Module {
	public function __construct() {
		$this->loader = false;
		$this->twig   = false;
	}

	/**
	 * Initialize Twig
	 * @return bool
	 */
	public function initTwig() {
		if (empty($this->loader) === false || empty($this->twig) === false) {
			return true;
		}
		$this->loader = new FilesystemLoader($this->config->paths->root.$this->path);
		$this->twig   = $this->createTwig();
		return true;
	}

	/**
	 * Return Twig Environment
	 * @return Environment
	 */
	public function createTwig() {
		$twig = new Environment($this->loader, [
			'cache'       => $this->config->paths->root.$this->cachepath,
			'auto_reload' => true,
			'debug'       => boolval($this->debug)
		]);
		TwigDecorator::decorate($twig, $this->loader);
		return $twig;
	}
}
