<?php namespace ProcessWire;

include_once(__DIR__.'/vendor/autoload.php');

// Dotenv
use Dotenv;
// Dpay
use Dpay\Db\Database;

/**
 * Dpay
 * Module for Autoloading Dpay
 */
class Dpay extends WireData implements Module {
	public function init() {
		$this->initEnv();
		$this->initDb();
	}

	public function initEnv() {
		$env = Dotenv\Dotenv::createImmutable(__DIR__);
		$env->load();
	}

	public function initDb() {
		Database::connect();
	}



	public static function getModuleInfo() {
		$infoArray = array(
			'title' => __('Dpay'),
			'version' => 115,
			'summary' => __("Autoloads Dpay"),
			'autoload' => true,
			'singular' => true,
			'author' => 'pauldro',
			'icon' => 'database'
		);
		return $infoArray;
	}
}
