<?php namespace ProcessWire;

include_once(__DIR__.'/vendor/autoload.php');
// App
use App\Ecomm;
use App\Pw\Hooks;
use App\Site;

/**
 * App
 * Module for Autoloading App classes
 */
class App extends WireData implements Module {
	public function init() {
		Hooks\ApiUrls::addHooks();
		Hooks\Sanitizer::addHooks();
		Hooks\Session::addHooks();
		Hooks\User::addHooks();
		Hooks\WireInput::addHooks();
		
		Ecomm\Pages\Hooks\PageProduct::addHooks();
		Ecomm\Pages\Hooks\PageProductsItemGroup::addHooks();
		Site\Pages\Hooks\Blog::addHooks();
		Site\Pages\Hooks\BlogPost::addHooks();

		$this->ecommDB = new WireData();
		$this->ecommDB->states = Ecomm\Database\States::instance();
		$this->ecommDB->cart   = Ecomm\Database\Cart::instance();
	}

	public static function getModuleInfo() {
		$infoArray = array(
			'title' => __('App'),
			'version' => 115,
			'summary' => __("Autoloads App Specific Classes, add Hooks"),
			'autoload' => true,
			'singular' => true,
			'author' => 'pauldro',
			'icon' => 'plug'
		);
		return $infoArray;
	}
}
